name: Metrics
on:
  # Runs every 6 hours
  schedule: [{cron: "0 */6 * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Base sections
          base: header, activity, community, repositories, metadata

          # Plugins
          plugin_isocalendar: yes
          plugin_activity: yes
          plugin_activity_days: 14        # Past 2 weeks
          plugin_activity_filter: all     # Show commits, PRs, issues, reviews
          plugin_activity_limit: 5
          plugin_activity_visibility: public

