name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]  # Runs every hour
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Base stats
          base: header, activity, community, repositories, metadata

          # Enable activity plugin (this gives you the radar chart)
          plugin_activity: yes
          plugin_activity_days: 14      # Past 2 weeks
          plugin_activity_filter: all   # Show commits, PRs, issues, reviews
          plugin_activity_limit: 5
          plugin_activity_visibility: public
          plugin_activity_timestamps: yes
          plugin_activity_skipped: no
